[project]
name = "py-emu-chip8"
version = "0.1.0"
description = "An emulator for the CHIP-8 interpreted programming language."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.4.1",
    "pyglet>=2.1.12",
]
